# Developer's Note: This is a sample _config.yml file offered with
# jekyll-theme-prologue for your convenience. To use it, move it to your
# project's root directory. Please note that the following lines are
# NECESSARY for Prologue to work correctly:
#
# theme: jekyll-theme-prologue
# collections: [sections]
#
# They activate the theme and tell Jekyll to find your homepage content
# in /_sections. Note where "sections" starts with an underscore
# and where it doesn't. The social settings will make links to
# Twitter, etc., but only if you give the URL.
#
# Also, be sure to customize url and baseurl for your site.
#
# ---------------------------------------------------------------
#
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The DE-TEL Book
subtitle: Doctoral Education for Technology Enhanced Learning
description: >- # this means to ignore newlines until "baseurl:"
  The Open book on Doctoral Education in Technology Enhanced Learning (DETEL book) is an open educational resource for doctoral candidates working in the field of Technology-Enhanced Learning or TEL (also known as Educational Technology, Digitl Education, Learning Engineering) and related fields.
author: DE-TEL
email:

# You'll want to customize url and baseurl for your own site:
baseurl: "/detel-book" # the subpath of your site, e.g. /blog
url: "https://ea-tel.github.io" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url: https://twitter.com/eateleu
facebook_url: https://www.facebook.com/eatel.eu
discord_url: https://discord.gg/T4sXEu5f92
instagram_url:
linkedin_url:
github_url: https://github.com/ea-tel/detel-book
stackoverflow_url:
pinterest_url:
slack_url:
dribbble_url:
feed_url: https://ea-tel.eu/detel-book/feed.xml

# Social Tags
og_image: /assets/images/Cover.png
image: /assets/images/Cover.png
logo: /assets/images/Cover.png

twitter:
  username: eateleu
  site: https://twitter.com/eateleu

facebook:
 publisher: https://www.facebook.com/eatel.eu

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-prologue
collections: [sections]

# Build settings
markdown: kramdown
exclude: ["README.md"]
include:
  - _chapters/chapters
  - _chapters
sass:
    sass_dir: _sass
    style: compressed

# Plugin settings
scholar:
    relative: "/detel-book/bibliography.html"

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag